In [1]:
from google.colab import drive
drive.mount('/content/gdrive/')
import numpy as np
import math
import pandas as pd
from sklearn.model_selection import train_test_split

Mounted at /content/gdrive/

In [2]:
name = 'MovieLen100k'


#Đọc dataset
df = pd.read_excel(r'/content/gdrive/MyDrive/Luận văn/{0}/{0}.xlsx'.format(name), dtype={'User': int, 'Item': str})
df

       User   Item  Rating
0         1  37367       5
1         1   8651       5
2         1   8829       4
3         1  26527       5
4         1  49599       5
...     ...    ...     ...
80831  1000   3007       5
80832  1000  30156       5
80833  1000  23921       5
80834  1000  21932       5
80835  1000  50224       5

[80836 rows x 3 columns]

In [3]:
#Chia training
training_df = df.sample(frac=0.8,random_state=0)
training_df

       User   Item  Rating
2816     29  26989       5
48140   386  22512       5
7260     70   8288       5
54598   480  47189       5
65842   674  27762       5
...     ...    ...     ...
27756   211   7778       5
78117   928   8703       5
12022   104  18555       5
9688     81  26192       5
22379   185  20191       5

[64669 rows x 3 columns]

In [4]:
#Chia testing
testing_df = df.drop(training_df.index)
testing_df

       User   Item  Rating
2         1   8829       4
10        1  25009       5
13        1  22384       4
20        1  14163       5
21        1  50601       5
...     ...    ...     ...
80804   999  36024       5
80810   999  27756       5
80816   999   7482       5
80820   999  26704       5
80824  1000  20138       4

[16167 rows x 3 columns]

In [5]:
#Lưu file training
training_df.to_excel('/content/gdrive/MyDrive/Luận văn/{0}/{0}_training.xlsx'.format(name), index=False)

#Lưu file testing
testing_df.to_excel('/content/gdrive/MyDrive/Luận văn/{0}/{0}_testing.xlsx'.format(name), index=False)